// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRDrinkOrder.Shared.Models;

#nullable disable

namespace QRDrinkOrder.Shared.Migrations
{
    [DbContext(typeof(QrdrinkOrderDbContext))]
    partial class QrdrinkOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RoleID");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA5866FDE3939");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Accounts__A9D1053403132823")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5499A8951FD95E");

                    b.HasIndex("AccountId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.BankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BankAccountId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B1E0922B6");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CategoryTranslation", b =>
                {
                    b.Property<int>("CategoryTranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryTranslationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryTranslationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("CategoryTranslationId")
                        .HasName("PK__Category__403F34FB79847652");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTranslations");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CouponID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DiscountType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinOrderValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CouponId")
                        .HasName("PK__Coupons__384AF1DAA6F16E8D");

                    b.HasIndex(new[] { "CouponCode" }, "UQ__Coupons__D34908007458F87A")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CouponUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("CouponID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UsageId")
                        .HasName("PK__CouponUs__29B197C028A86D3B");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "CouponId", "Phone" }, "UX_Coupon_Phone")
                        .IsUnique();

                    b.ToTable("CouponUsages");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CustomerSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PreferredLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("vi")
                        .IsFixedLength();

                    b.HasKey("SessionId")
                        .HasName("PK__Customer__C9F492701963CAE8");

                    b.HasIndex(new[] { "Phone" }, "IX_CustomerSessions_Phone");

                    b.ToTable("CustomerSessions");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinkId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte?>("TemperatureType")
                        .HasColumnType("tinyint");

                    b.HasKey("DrinkId")
                        .HasName("PK__Drinks__C094D3C8A1032C6A");

                    b.HasIndex("CategoryId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.DrinkTranslation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TranslationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int")
                        .HasColumnName("DrinkID");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("TranslationId")
                        .HasName("PK__DrinkTra__663DA0ACB15C22A2");

                    b.HasIndex("DrinkId");

                    b.ToTable("DrinkTranslations");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04FF185C9DB36");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Employee__349DA587D8C40403")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ManagerId")
                        .HasName("PK__Managers__3BA2AA81672BAF8C");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Managers__349DA587206538A8")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MembershipId")
                        .HasName("PK__Membership__12345678");

                    b.HasIndex(new[] { "Phone" }, "UQ__Membership__Phone")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("CouponID");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<decimal?>("FinalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([TotalAmount]-[DiscountAmount])", false);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte?>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("PointsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID");

                    b.Property<string>("TableNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFF76502E2");

                    b.HasIndex("CouponId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "OrderDate" }, "IX_Orders_Date");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("DrinkId")
                        .HasColumnType("int")
                        .HasColumnName("DrinkID");

                    b.Property<byte?>("IceLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("ItemNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", false);

                    b.Property<byte?>("SweetnessLevel")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__57ED06A153CE0FD5");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.OrderItemTopping", b =>
                {
                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId", "ToppingId")
                        .HasName("PK__OrderItemTopping");

                    b.HasIndex("ToppingId");

                    b.ToTable("OrderItemToppings");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TransactionID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A5816726265");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Payments__C3905BAE210CF8AF")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.PointHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PointsChanged")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HistoryId")
                        .HasName("PK__PointHistory__12345678");

                    b.HasIndex("Phone");

                    b.ToTable("PointHistories");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("CouponID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42F2FC033942A");

                    b.HasIndex("CouponId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.PromotionTranslation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TranslationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TranslationId")
                        .HasName("PK__Promotio__663DA0AC27E05244");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionTranslations");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.PushSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P256DH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__PushSubscription__12345678");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AE30D12490");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Reviews__C3905BAEF421A0F6")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.ReviewImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ImageId")
                        .HasName("PK__ReviewIm__7516F4ECDFF38E6C");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A1F1B8206");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceOffset")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SizeId")
                        .HasName("PK__Size");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.StaffBenefit", b =>
                {
                    b.Property<int>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BenefitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateOnly?>("UsedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.HasKey("BenefitId")
                        .HasName("PK__StaffBen__5754C53A9A8852D5");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.ToTable("StaffBenefits");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ConfigKey")
                        .HasName("PK__SystemConfig__12345678");

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToppingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ToppingId")
                        .HasName("PK__Topping");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Account", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Accounts__RoleID__5070F446");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.AuditLog", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Account", "Account")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__AuditLogs__Accou__14270015");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CategoryTranslation", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CategoryT__Categ__5FB337D6");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CouponUsage", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Coupon", "Coupon")
                        .WithMany("CouponUsages")
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK__CouponUsa__Coupo__22751F6C");

                    b.HasOne("QRDrinkOrder.Shared.Models.Order", "Order")
                        .WithMany("CouponUsages")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__CouponUsa__Order__236943A5");

                    b.Navigation("Coupon");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Drink", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Category", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Drinks__Category__6477ECF3");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.DrinkTranslation", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Drink", "Drink")
                        .WithMany("DrinkTranslations")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DrinkTran__Drink__6754599E");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Employee", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Account", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("QRDrinkOrder.Shared.Models.Employee", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Employees__Accou__5812160E");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Manager", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Account", "Account")
                        .WithOne("Manager")
                        .HasForeignKey("QRDrinkOrder.Shared.Models.Manager", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Managers__Accoun__5441852A");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Order", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK__Orders__CouponID__02084FDA");

                    b.HasOne("QRDrinkOrder.Shared.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Orders__Employee__01142BA1");

                    b.HasOne("QRDrinkOrder.Shared.Models.CustomerSession", "Session")
                        .WithMany("Orders")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__SessionI__00200768");

                    b.Navigation("Coupon");

                    b.Navigation("Employee");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.OrderItem", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Drink", "Drink")
                        .WithMany("OrderItems")
                        .HasForeignKey("DrinkId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Drink__06CD04F7");

                    b.HasOne("QRDrinkOrder.Shared.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__05D8E0BE");

                    b.HasOne("QRDrinkOrder.Shared.Models.Size", "Size")
                        .WithMany("OrderItems")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__OrderItem__Size");

                    b.Navigation("Drink");

                    b.Navigation("Order");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.OrderItemTopping", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.OrderItem", "OrderItem")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderItemTopping__OrderItem");

                    b.HasOne("QRDrinkOrder.Shared.Models.Topping", "Topping")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderItemTopping__Topping");

                    b.Navigation("OrderItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Payment", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("QRDrinkOrder.Shared.Models.Payment", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__OrderI__0B91BA14");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.PointHistory", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Membership", "Membership")
                        .WithMany("PointHistories")
                        .HasForeignKey("Phone")
                        .HasPrincipalKey("Phone")
                        .IsRequired()
                        .HasConstraintName("FK__PointHistory__Membership");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Promotion", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Coupon", "Coupon")
                        .WithMany("Promotions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Promotion__Coupo__72C60C4A");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.PromotionTranslation", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Promotion", "Promotion")
                        .WithMany("PromotionTranslations")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Promotion__Promo__75A278F5");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Review", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("QRDrinkOrder.Shared.Models.Review", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__OrderID__19DFD96B");

                    b.HasOne("QRDrinkOrder.Shared.Models.CustomerSession", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Session__1AD3FDA4");

                    b.Navigation("Order");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.ReviewImage", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReviewIma__Revie__1EA48E88");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.StaffBenefit", b =>
                {
                    b.HasOne("QRDrinkOrder.Shared.Models.Employee", "Employee")
                        .WithMany("StaffBenefits")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__StaffBene__Emplo__0F624AF8");

                    b.HasOne("QRDrinkOrder.Shared.Models.Order", "Order")
                        .WithMany("StaffBenefits")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__StaffBene__Order__10566F31");

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Coupon", b =>
                {
                    b.Navigation("CouponUsages");

                    b.Navigation("Orders");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.CustomerSession", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Drink", b =>
                {
                    b.Navigation("DrinkTranslations");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Employee", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("StaffBenefits");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Membership", b =>
                {
                    b.Navigation("PointHistories");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Order", b =>
                {
                    b.Navigation("CouponUsages");

                    b.Navigation("OrderItems");

                    b.Navigation("Payment");

                    b.Navigation("Review");

                    b.Navigation("StaffBenefits");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.OrderItem", b =>
                {
                    b.Navigation("OrderItemToppings");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Promotion", b =>
                {
                    b.Navigation("PromotionTranslations");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Size", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QRDrinkOrder.Shared.Models.Topping", b =>
                {
                    b.Navigation("OrderItemToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
